<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Редактировать коллекцию' => 'Редактировать коллекцию',
    'Удалить коллекцию' => 'Удалить коллекцию',
    'Редактировать временную коллекцию' => 'Редактировать временную коллекцию',
    'Удалить временную коллекцию' => 'Удалить временную коллекцию',
    'Создание коллекции' => 'Создание коллекции',
    'Создание временной коллекции' => 'Создание временной коллекции',
    'Редактирование коллекции' => 'Редактирование коллекции',
    'Редактирование временной коллекции' => 'Редактирование временной коллекции',
    'Коллекции' => 'Коллекции',
    'Создать коллекцию' => 'Создать коллекцию',
    'Создать временную коллекцию' => 'Создать временную коллекцию',
    'Родительская коллекция' => 'Родительская коллекция',
    'Временная коллекция' => 'Временная коллекция',
    'Открытая временная коллекция' => 'Открытая временная коллекция',
    'Нет родительской коллекции' => 'Нет родительской коллекции',
    'Обычная коллекция не может быть открытой!' => 'Обычная коллекция не может быть открытой!',
    'Добавить во временную коллекцию' => 'Добавить во временную коллекцию',
    'Объекты в коллекции' => 'Объекты в коллекции',
    'Дочерние коллекции' => 'Дочерние коллекции',
    'У временной коллекции не может быть родительской коллекции!' => 'У временной коллекции не может быть родительской коллекции!'

);
